// Mock data for the Vietnamese beverage e-commerce site
// This can be replaced with actual database queries later

export interface Product {
  id: string
  name: string
  nameVi: string
  description: string
  descriptionVi: string
  price: number
  image: string
  category: "che" | "sinh-to" | "tra" | "nuoc-ep"
  featured: boolean
  inStock: boolean
}

export interface Category {
  id: string
  name: string
  nameVi: string
  slug: string
  description: string
  image: string
}

export const categories: Category[] = [
  {
    id: "1",
    name: "Chè",
    nameVi: "Chè",
    slug: "che",
    description: "Traditional Vietnamese sweet dessert soups",
    image: "/vietnamese-che-dessert-colorful-beans.jpg",
  },
  {
    id: "2",
    name: "Sinh tố",
    nameVi: "Sinh Tố",
    slug: "sinh-to",
    description: "Fresh Vietnamese fruit smoothies",
    image: "/vietnamese-smoothie-avocado-tropical-fruit.jpg",
  },
  {
    id: "3",
    name: "Trà",
    nameVi: "Trà",
    slug: "tra",
    description: "Refreshing Vietnamese teas",
    image: "/vietnamese-iced-tea-jasmine-refreshing.jpg",
  },
  {
    id: "4",
    name: "Nước Ép",
    nameVi: "Nước Ép",
    slug: "nuoc-ep",
    description: "Fresh pressed juices and beverages",
    image: "/fresh-juice-bar-colorful-drinks.jpg",
  },
]

export const products: Product[] = [
  // Chè products (13 items from menu)
  {
    id: "1",
    name: "Chè Ba Màu",
    nameVi: "Chè Ba Màu",
    description: "Three-color dessert with beans, jelly, and coconut milk",
    descriptionVi: "Chè ba màu với đậu, thạch và nước cốt dừa",
    price: 45000,
    image: "/anhquan/che-ba-mau.jpg",
    category: "che",
    featured: true,
    inStock: true,
  },
  {
    id: "2",
    name: "Chè Thái",
    nameVi: "Chè Thái",
    description: "Mixed fruit dessert with coconut milk and crushed ice",
    descriptionVi: "Chè trái cây tổng hợp với nước cốt dừa và đá bào",
    price: 50000,
    image: "/che-thai-mixed-fruit-dessert-colorful.jpg",
    category: "che",
    featured: true,
    inStock: true,
  },
  {
    id: "3",
    name: "Chè Đậu Đen",
    nameVi: "Chè Đậu Đen",
    description: "Sweet black bean dessert soup",
    descriptionVi: "Chè đậu đen ngọt mát",
    price: 35000,
    image: "/anhquan/che-dau-den.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "4",
    name: "Chè Đậu Xanh",
    nameVi: "Chè Đậu Xanh",
    description: "Mung bean dessert soup",
    descriptionVi: "Chè đậu xanh mát lạnh",
    price: 35000,
    image: "/anhquan/che-dau-xanh.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "5",
    name: "Chè Khúc Bạch",
    nameVi: "Chè Khúc Bạch",
    description: "White jelly dessert with longan",
    descriptionVi: "Chè khúc bạch với nhãn",
    price: 40000,
    image: "/anhquan/che-khuc-bach.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "6",
    name: "Sâm Bổ Lượng",
    nameVi: "Sâm Bổ Lượng",
    description: "Herbal jelly dessert with dried fruits",
    descriptionVi: "Sâm bổ lượng với hạt sen và hạt ý dĩ",
    price: 45000,
    image: "/sam-bo-luong-vietnamese-herbal-dessert.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "7",
    name: "Cocktail Trái Cây",
    nameVi: "Cocktail Trái Cây",
    description: "Fresh fruit cocktail dessert",
    descriptionVi: "Cocktail trái cây tươi mát",
    price: 48000,
    image: "/vietnamese-fruit-cocktail-dessert-colorful.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "8",
    name: "Trái Cây Tô",
    nameVi: "Trái Cây Tô",
    description: "Mixed fruit bowl dessert",
    descriptionVi: "Trái cây tô tổng hợp",
    price: 50000,
    image: "/vietnamese-mixed-fruit-bowl-dessert.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "9",
    name: "Cam Vắt",
    nameVi: "Cam Vắt",
    description: "Fresh squeezed orange juice",
    descriptionVi: "Cam vắt tươi nguyên chất",
    price: 35000,
    image: "/fresh-squeezed-orange-juice-vietnamese.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "10",
    name: "Đá Me",
    nameVi: "Đá Me",
    description: "Tamarind iced drink",
    descriptionVi: "Đá me chua ngọt giải khát",
    price: 30000,
    image: "/tamarind-iced-drink-vietnamese.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "11",
    name: "Bánh Flan",
    nameVi: "Bánh Flan",
    description: "Vietnamese caramel custard",
    descriptionVi: "Bánh flan caramen mềm mịn",
    price: 25000,
    image: "/vietnamese-flan-caramel-custard.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "12",
    name: "Rau Câu Trái Dừa",
    nameVi: "Rau Câu Trái Dừa",
    description: "Coconut jelly dessert",
    descriptionVi: "Rau câu trái dừa mát lạnh",
    price: 35000,
    image: "/coconut-jelly-dessert-vietnamese.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },
  {
    id: "13",
    name: "Milo Đá Trân Châu",
    nameVi: "Milo Đá Trân Châu",
    description: "Iced Milo with tapioca pearls",
    descriptionVi: "Milo đá trân châu đường đen",
    price: 40000,
    image: "/anhquan/milo-da-tran-chau.jpg",
    category: "che",
    featured: false,
    inStock: true,
  },

  // Sinh Tố products (13 items from menu)
  {
    id: "14",
    name: "Sinh Tố Bơ",
    nameVi: "Sinh Tố Bơ",
    description: "Creamy avocado smoothie",
    descriptionVi: "Sinh tố bơ béo ngậy",
    price: 55000,
    image: "/anhquan/sinh-to-bo.jpg",
    category: "sinh-to",
    featured: true,
    inStock: true,
  },
  {
    id: "15",
    name: "Sinh Tố Dâu",
    nameVi: "Sinh Tố Dâu",
    description: "Fresh strawberry smoothie",
    descriptionVi: "Sinh tố dâu tươi mát",
    price: 48000,
    image: "/anhquan/sinh-to-dau.jpg",
    category: "sinh-to",
    featured: true,
    inStock: true,
  },
  {
    id: "16",
    name: "Sinh Tố Lê",
    nameVi: "Sinh Tố Lê",
    description: "Fresh pear smoothie",
    descriptionVi: "Sinh tố lê mát lạnh",
    price: 45000,
    image: "/pear-smoothie-fresh-vietnamese.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "17",
    name: "Sinh Tố Táo",
    nameVi: "Sinh Tố Táo",
    description: "Fresh apple smoothie",
    descriptionVi: "Sinh tố táo tươi ngon",
    price: 45000,
    image: "/apple-smoothie-fresh-vietnamese.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "18",
    name: "Sinh Tố Xoài",
    nameVi: "Sinh Tố Xoài",
    description: "Sweet mango smoothie",
    descriptionVi: "Sinh tố xoài ngọt lịm",
    price: 52000,
    image: "/mango-smoothie-tropical-yellow-fresh.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "19",
    name: "Sinh Tố Mít",
    nameVi: "Sinh Tố Mít",
    description: "Jackfruit smoothie",
    descriptionVi: "Sinh tố mít thơm ngon",
    price: 50000,
    image: "/jackfruit-smoothie-vietnamese-tropical.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "20",
    name: "Sinh Tố Đào",
    nameVi: "Sinh Tố Đào",
    description: "Peach smoothie",
    descriptionVi: "Sinh tố đào ngọt mát",
    price: 48000,
    image: "/peach-smoothie-fresh-vietnamese.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "21",
    name: "Sinh Tố Dứa",
    nameVi: "Sinh Tố Dứa",
    description: "Pineapple smoothie",
    descriptionVi: "Sinh tố dứa chua ngọt",
    price: 45000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "22",
    name: "Sinh Tố Cacao Dừa",
    nameVi: "Sinh Tố Cacao Dừa",
    description: "Cacao coconut smoothie",
    descriptionVi: "Sinh tố cacao dừa béo ngậy",
    price: 55000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "23",
    name: "Sinh Tố Dư Dử",
    nameVi: "Sinh Tố Dư Dử",
    description: "Papaya smoothie",
    descriptionVi: "Sinh tố dư dử tươi mát",
    price: 45000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "24",
    name: "Sinh Tố Cà Rốt",
    nameVi: "Sinh Tố Cà Rốt",
    description: "Carrot smoothie",
    descriptionVi: "Sinh tố cà rốt bổ dưỡng",
    price: 42000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "25",
    name: "Sinh Tố Cà Chua",
    nameVi: "Sinh Tố Cà Chua",
    description: "Tomato smoothie",
    descriptionVi: "Sinh tố cà chua tươi mát",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "26",
    name: "Sinh Tố Măng Cầu",
    nameVi: "Sinh Tố Măng Cầu",
    description: "Soursop smoothie",
    descriptionVi: "Sinh tố măng cầu thơm ngon",
    price: 50000,
    image: "/soursop-smoothie-tropical-white-fruit.jpg",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "27",
    name: "Sinh Tố Sầu Riêng",
    nameVi: "Sinh Tố Sầu Riêng",
    description: "Durian smoothie",
    descriptionVi: "Sinh tố sầu riêng đặc biệt",
    price: 60000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "28",
    name: "Sinh Tố Thập Cẩm",
    nameVi: "Sinh Tố Thập Cẩm",
    description: "Mixed fruit smoothie",
    descriptionVi: "Sinh tố thập cẩm nhiều loại trái cây",
    price: 55000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "29",
    name: "Sinh Tố Sapoche",
    nameVi: "Sinh Tố Sapoche",
    description: "Sapodilla smoothie",
    descriptionVi: "Sinh tố sapoche ngọt tự nhiên",
    price: 48000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "30",
    name: "Sinh Tố Phúc Bồn Tử",
    nameVi: "Sinh Tố Phúc Bồn Tử",
    description: "Raspberry smoothie",
    descriptionVi: "Sinh tố phúc bồn tử chua ngọt",
    price: 52000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },
  {
    id: "31",
    name: "Sinh Tố Việt Quất",
    nameVi: "Sinh Tố Việt Quất",
    description: "Blueberry smoothie",
    descriptionVi: "Sinh tố việt quất bổ dưỡng",
    price: 55000,
    image: "/placeholder.svg?height=400&width=400",
    category: "sinh-to",
    featured: false,
    inStock: true,
  },

  // Trà products (14 items from menu)
  {
    id: "32",
    name: "Trà Sữa Truyền Thống",
    nameVi: "Trà Sữa Truyền Thống",
    description: "Traditional milk tea",
    descriptionVi: "Trà sữa truyền thống đậm đà",
    price: 45000,
    image: "/anhquan/tra-sua-truyen-thong.jpg",
    category: "tra",
    featured: true,
    inStock: true,
  },
  {
    id: "33",
    name: "Trà Sữa Thái Xanh",
    nameVi: "Trà Sữa Thái Xanh",
    description: "Thai green milk tea",
    descriptionVi: "Trà sữa Thái xanh thơm mát",
    price: 48000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "34",
    name: "Sữa Tươi Trân Châu Đường Đen",
    nameVi: "Sữa Tươi Trân Châu Đường Đen",
    description: "Fresh milk with brown sugar tapioca",
    descriptionVi: "Sữa tươi trân châu đường đen béo ngậy",
    price: 50000,
    image: "/anhquan/sua-tuoi-tran-chau-duong-den.jpg",
    category: "tra",
    featured: true,
    inStock: true,
  },
  {
    id: "35",
    name: "Trà Sen",
    nameVi: "Trà Sen",
    description: "Lotus tea",
    descriptionVi: "Trà sen thơm nhẹ thanh mát",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "36",
    name: "Trà Vải",
    nameVi: "Trà Vải",
    description: "Lychee tea",
    descriptionVi: "Trà vải ngọt mát",
    price: 42000,
    image: "/lychee-tea-sweet-pink-vietnamese.jpg",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "37",
    name: "Trà Đào",
    nameVi: "Trà Đào",
    description: "Peach tea",
    descriptionVi: "Trà đào thơm ngọt",
    price: 42000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "38",
    name: "Trà Dâu",
    nameVi: "Trà Dâu",
    description: "Strawberry tea",
    descriptionVi: "Trà dâu chua ngọt",
    price: 42000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "39",
    name: "Trà Thơm",
    nameVi: "Trà Thơm",
    description: "Pineapple tea",
    descriptionVi: "Trà thơm chua ngọt giải khát",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "40",
    name: "Trà Tắc",
    nameVi: "Trà Tắc",
    description: "Kumquat tea",
    descriptionVi: "Trà tắc chua thanh mát",
    price: 38000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "41",
    name: "Trà Chanh Dây",
    nameVi: "Trà Chanh Dây",
    description: "Passion fruit tea",
    descriptionVi: "Trà chanh dây chua ngọt",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "42",
    name: "Trà Măng Cầu",
    nameVi: "Trà Măng Cầu",
    description: "Soursop tea",
    descriptionVi: "Trà măng cầu thơm mát",
    price: 42000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "43",
    name: "Trà Đặc Thơm",
    nameVi: "Trà Đặc Thơm",
    description: "Special aromatic tea",
    descriptionVi: "Trà đặc thơm đậm đà",
    price: 45000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "44",
    name: "Hồng Trà Trân Châu",
    nameVi: "Hồng Trà Trân Châu",
    description: "Black tea with tapioca pearls",
    descriptionVi: "Hồng trà trân châu đường đen",
    price: 45000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },
  {
    id: "45",
    name: "Đầy Đủ Thạch Nhà Làm",
    nameVi: "Đầy Đủ Thạch Nhà Làm",
    description: "Tea with homemade jelly",
    descriptionVi: "Trà với thạch nhà làm đủ vị",
    price: 42000,
    image: "/placeholder.svg?height=400&width=400",
    category: "tra",
    featured: false,
    inStock: true,
  },

  // Nước Ép products (11 items from menu)
  {
    id: "46",
    name: "Nước Ép Táo",
    nameVi: "Nước Ép Táo",
    description: "Fresh apple juice",
    descriptionVi: "Nước ép táo tươi nguyên chất",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "47",
    name: "Nước Ép Lê",
    nameVi: "Nước Ép Lê",
    description: "Fresh pear juice",
    descriptionVi: "Nước ép lê tươi mát",
    price: 40000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "48",
    name: "Nước Ép Thơm",
    nameVi: "Nước Ép Thơm",
    description: "Fresh pineapple juice",
    descriptionVi: "Nước ép thơm tươi chua ngọt",
    price: 38000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "49",
    name: "Nước Ép Dưa Hấu",
    nameVi: "Nước Ép Dưa Hấu",
    description: "Fresh watermelon juice",
    descriptionVi: "Nước ép dưa hấu tươi mát",
    price: 35000,
    image: "/anhquan/nuoc-ep-dua-hau.jpg",
    category: "nuoc-ep",
    featured: true,
    inStock: true,
  },
  {
    id: "50",
    name: "Nước Ép Cà Rốt",
    nameVi: "Nước Ép Cà Rốt",
    description: "Fresh carrot juice",
    descriptionVi: "Nước ép cà rốt bổ dưỡng",
    price: 38000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "51",
    name: "Nước Ép Cà Chua",
    nameVi: "Nước Ép Cà Chua",
    description: "Fresh tomato juice",
    descriptionVi: "Nước ép cà chua tươi mát",
    price: 35000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "52",
    name: "Yaourt Đá",
    nameVi: "Yaourt Đá",
    description: "Iced yogurt drink",
    descriptionVi: "Yaourt đá mát lạnh",
    price: 30000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "53",
    name: "Sỉ Rô Đá Bào",
    nameVi: "Sỉ Rô Đá Bào",
    description: "Shaved ice with syrup",
    descriptionVi: "Sỉ rô đá bào nhiều vị",
    price: 25000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "54",
    name: "Soda Mix Vị",
    nameVi: "Soda Mix Vị",
    description: "Mixed flavor soda",
    descriptionVi: "Soda mix nhiều vị tươi mát",
    price: 30000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "55",
    name: "Sâm Dừa Sữa",
    nameVi: "Sâm Dừa Sữa",
    description: "Coconut milk with grass jelly",
    descriptionVi: "Sâm dừa sữa mát lạnh",
    price: 35000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "56",
    name: "Rau Má Đậu Xanh",
    nameVi: "Rau Má Đậu Xanh",
    description: "Pennywort and mung bean drink",
    descriptionVi: "Rau má đậu xanh mát gan",
    price: 35000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
  {
    id: "57",
    name: "Nước Ngọt Các Loại",
    nameVi: "Nước Ngọt Các Loại",
    description: "Various soft drinks",
    descriptionVi: "Nước ngọt các loại",
    price: 20000,
    image: "/placeholder.svg?height=400&width=400",
    category: "nuoc-ep",
    featured: false,
    inStock: true,
  },
]

export function getProducts() {
  return products
}

export function getProductById(id: string) {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured)
}

export function getCategories() {
  return categories
}
